name: 打包并发布 Chrome 扩展

on:
  push:
    branches:
      - main  # 仅在推送到主分支时触发
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 创建 Chrome 扩展的 ZIP 文件
        run: |
          cd chrome-extension
          zip -r ../chrome-extension.zip .

      - name: 获取版本号
        id: get_version
        run: |
          VERSION=$(node -p "require('./chrome-extension/package.json').version" 2>/dev/null || echo "v0.0.1")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "New version:${VERSION}"

      - name: 创建 Release 并上传 ZIP 文件
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.VERSION }}
          name: v${{ env.VERSION }}
          files: chrome-extension.zip
